### ISSUE TITLE
Incorrect data format for 12_month_enrollment Part B CREDHRSU

### ISSUE THREAD

**Issue by edwelch802** [AlisonLanski/IPEDSuploadables#112]
**Describe the bug**
The data type for the 12-month enrollment text file is a real number and not integer and contains commas.

**To Reproduce**
1. Run produce_e1d_report.R script
2. Upload resulting text file to IPEDS
3. An error message will be generated

**Expected behavior**
No error messages generated by IPEDS upload process

**Screenshots**
Not available

**Technical Setup (please complete the following information):**
 - OS type: Windows
 - R version: 4.3.1
 - Package version: 2.8.5

**Additional context**
The original data value was 62,033.0. Once I deleted the comma and decimal and trailing 0. The file uploaded with no errors.

**Comment by edwelch802** [comment]
Discovered that the data pull routine had written the value as 62,033.0, thus it was an error with the data pull and not the R script. I apologize for the confusion.

**Comment by AlisonLanski** [comment]
Best possible sort of issue post, since we don't need to do anthing! :}  I'm glad you got it worked out
