### ISSUE TITLE
produce_om_report; Certs and  Degrees same record, same award period

### ISSUE THREAD

**Issue by Chicago-Dave** [AlisonLanski/IPEDSuploadables#128]
**Please fill out all sections on here so we can assist you in a timely manner!**

**Reporting two awards for the same record line**

1. STUDENT ID:AWARDLEVEL4
2. 3, 1

**Expected behavior**
Unclear how to handle instances where the student is awarded both a BA and a Cert at the same graduation time; One solution is to manually alter the existing section in the uploadable text for the certs which seems out of character for the suite of functions.

**Additional context**
We are reporting 23 instances where the same student earned both a BA and a Cert. Instances where a Cert award only is no problem.

mutate(AwardLevel4 = case_when(
    Completers == 'AwardStatus4Years' & `DegreeType01` == 'BA' ~ 3,
    Completers == 'AwardStatus4Years' & `DegreeType01` == 'CC' ~ 1,
    TRUE ~ 4
  )) %>% 

If we were to add a line for DegreeType02 == 'CC' ~ 1, it would overwrite the '3' for the BA for those 23 students.

Thanks for all the work you have put into ipedsUploadables!

David Thomas

**Comment by AlisonLanski** [comment]
I'm so sorry I missed this.   Gmail categorized it as "not important".  (Silly Gmail)
  
According to the [IPEDS OM FAQs](https://surveys.nces.ed.gov/ipeds/public/survey-materials/faq?faqid=14), only the "highest degree" should be reported on the survey:  
  
> If a student earns multiple awards at my institution, do I count the higher award?
> 
> Yes, count the highest award received for each status point (i.e., four years, six years, and eight years). Regardless of whether the student earns multiple awards at your institution, only one award is reported per student, per status point. For example, if a student earned a certificate and Associate’s degree by the end of four years, the institution would report only the Associate’s degree. If the same student continues enrollment at the institution and earns a Bachelor’s degree by year seven, the institution would report the Associate’s degree at the six-year status point, but the Bachelor’s degree at the eight-year status point. The certificate award is never reported to OM in this example because it was not the highest award earned at any status point.
  
Assuming your students are earning these at the same time, you would want to limit your starting_df to only include the BA award.  If your students are NOT earning them at the same time... hmmm.  That is something I don't know that the package can handle at the moment. I wasn't aware that it was a use case, so I haven't tested for it.
  
So -- as a followup question --- A) are these awards happening at the same time, or B) at different times?  Either way, I should get things updated, but the urgency of my update depends on your answer :}

**Comment by AlisonLanski** [comment]
Ah I read your post again -- same time sounds like we're in situation A.  So that looks like a data update on your part.  And looking at my starting_df requirements, I think I"m also ok for situation B, since award status can be different in different years.  But I'll run some tests on that before closing this issue,

**Comment by AlisonLanski** [comment]
I checked with some test code, and if someone is coded as,. for example, CERTIFICATE in years 4 and 6 but BACHELORS in year 8, the values in year 8 will change to remove the CERTIFICATE level and add the BACHELORs level.  So I believe the package is behaving correctly, and will close this issue.
