### ISSUE TITLE
produce_om_report asking for COHORTSTATUS column

### ISSUE THREAD

**Issue by auppham** [AlisonLanski/IPEDSuploadables#129]
I prepared my data following the instructions outlined here: [https://alisonlanski.github.io/IPEDSuploadables/articles/setup_for_om](https://alisonlanski.github.io/IPEDSuploadables/articles/setup_for_om.html#to-use-the-produce_om_report-function-your-data-must-be-in-the-format-described-below)

Below is the structure of my_df:
> sapply(my_df, class)
       Unitid     StudentId    CohortType     Recipient     Exclusion   AwardLevel4   AwardLevel6   AwardLevel8 EnrollStatus8 
    "numeric"     "numeric"     "numeric"     "numeric"   "character"     "numeric"     "numeric"     "numeric"     "numeric" 

When I run the produce_om_report() function, I got this error:
> produce_om_report(df =my_df, part = "ALL", format = "uploadable")
Error in `dplyr::mutate()`:
ℹ In argument: `EXCLUSION = dplyr::case_when(...)`.
Caused by error in `dplyr::case_when()`:
! Failed to evaluate the left-hand side of formula 1.
Caused by error in `.data$COHORTSTATUS`:
! Column `COHORTSTATUS` not found in `.data`.

It seems the function is looking for a column named COHORTSTATUS, which is not present in the data frame. Based on the data format instructions, should the third column (CohortType) be renamed to CohortStatus, or is this a different column that is missing?

Here are my system details: Windows; R Version: 4.4.0; Package Version: 2.9.1

Thank you for your work on the package! It has been a tremendous help.

**Comment by AlisonLanski** [comment]
From looking at the code, it looks like we renamed the Exclusion column to CohortStatus but this didn't make it into the vignette with setup instructions.   Honestly, I'm amazed this wasn't caught earlier -- thank you for letting me know!
    
I will get the documentation updated (and maybe adjust the code to still accept "Exclusion" as a column name), but this will probably happen at the end of the week.   
  
If you're wanting to get this working immediately with 2.9.1, just rename your Exclusion column to CohortStatus.  If that doesn't solve it, let me know!

**Comment by AlisonLanski** [comment]
@auppham I submitted a new package version (2.10.0) to CRAN today with a fix for this.  It may take a couple days to become available for installation there. If you want is sooner, you can download the most recent version from github (the documentation website has sample code)

**Comment by auppham** [comment]
@AlisonLanski Thank you for working on this request! I'll wait a week before running everything again and let you know if the issue persists.
