### ISSUE TITLE
add scripts for fall enrollment

### ISSUE THREAD

**Issue by AlisonLanski** [AlisonLanski/IPEDSuploadables#18]
- [x] Write part A
- [x] Write part B
- [x] Write part C
- [x] Write part D
- [x] Write part E
- [x] Write part F
- [x] Write part G
- [x] Write prep function
- [x] Write wrapper function
- [x] Create google sheet for import specs
- [x] Create RMD vignette that reads in google sheet
- [x] Create dummy data
- [x] Test functions using dummy data
- [ ] Test functions using real data
- [x] Save dummy data as a .rda to the package
- [x] Save google sheet as .rda to the package
- [x] Run devtools::check() and address errors

**Comment by shilohfling** [comment]
need help with parts e & g. not sure about what data structure and inputs we want from the user.
