### ISSUE TITLE
add scripts for 12 month enrollment

### ISSUE THREAD

**Issue by AlisonLanski** [AlisonLanski/IPEDSuploadables#19]
- [x] Write part A
- [x] Write part B
- [x] Write part C
- [x] Write wrapper function
- [x] Create google sheet for import specs
- [x] Create RMD vignette that reads in google sheet
- [x] Create dummy data
- [x] Test functions using dummy data
- [x] Test functions using real data
- [x] Save dummy data as a .rda to the package
- [x] Save google sheet as .dat to the package
- [x] Run devtools::check() and address errors

**Comment by AlisonLanski** [comment]
@shilohfling I think this is done now but I would appreciate a once-over for documentation or running things using dummy data etc.

**Comment by shilohfling** [comment]
Validated baybeeee!!!
