### ISSUE TITLE
add scripts for graduation rates

### ISSUE THREAD

**Issue by AlisonLanski** [AlisonLanski/IPEDSuploadables#21]
- [x] Write part B
- [x] Write part C
- [x] Write prep function
- [x] Write wrapper function
- [x] Create google sheet for import specs
- [x] Create RMD vignette that reads in google sheet
- [x] Create dummy data
- [x] Test functions using dummy data
- [x] Test functions using real data
- [x] Save dummy data as a .rda to the package
- [x] Save google sheet as .rda to the package
- [x] Run devtools::check() and address errors
- [x] Rewrite google sheet and RMD for new df requirements

**Comment by shilohbradley** [comment]
Just need validation

**Comment by shilohbradley** [comment]
Why do we need this step:  Save google sheet as .dat to the package

**Comment by shilohbradley** [comment]
We need to discuss the data structure because Part B and Part C require different fields and could possibly have different students.

**Comment by shilohbradley** [comment]
devtools::check() output

> checking R code for possible problems ... NOTE
  Found the following assignments to the global environment:
  File 'IPEDSuploadables/R/set_report_path.R':
    assign(x = "output_path", value = path, envir = globalenv())

0 errors √ | 0 warnings √ | 1 note x

**Comment by AlisonLanski** [comment]
@AlisonLanski please validate
