### ISSUE TITLE
add scripts for outcome measures

### ISSUE THREAD

**Issue by AlisonLanski** [AlisonLanski/IPEDSuploadables#23]
- [x] Write part A
- [x] Write part B
- [x] Write part C
- [x] Write part D
- [x] Write prep function
- [x] Write wrapper function
- [x] Create google sheet for import specs
- [x] Create RMD vignette that reads in google sheet
- [x] Create dummy data
- [x] Test functions using dummy data
- [x] Test functions using real data
- [x] Save dummy data as a .rda to the package
- [x] Save google sheet as .dat to the package
- [x] Run devtools::check() and address errors

**Comment by shilohbradley** [comment]
- [ ] Write part A

- [ ] Write part B

- [ ] Write part C

- [ ] Write part D

- [ ] Write prep function

- [ ] Write wrapper function

- [ ] Create google sheet for import specs

- [ ] Create RMD vignette that reads in google sheet

- [ ] Create dummy data

- [ ] Test functions using dummy data

- [ ] Test functions using real data

- [ ] Save dummy data as a .rda to the package

- [ ] Save google sheet as .dat to the package

**Comment by AlisonLanski** [comment]
I don't think we need a prep function (?) the only thing I ran into was Unitid datatype in part D, so I did a transform there

**Comment by AlisonLanski** [comment]
@shilohfling please validate
