### ISSUE TITLE
write scripts for graduation rates 200

### ISSUE THREAD

**Issue by AlisonLanski** [AlisonLanski/IPEDSuploadables#27]
- [x] Write part A
- [x] Write prep function
- [x] Write wrapper function
- [x] Create google sheet for import specs
- [x] Create RMD vignette that reads in google sheet
- [x] Create dummy data
- [x] Test functions using dummy data
- [x] Test functions using real data
- [x] Save dummy data as a .rda to the package
- [x] Save google sheet as .dat to the package
- [x] Run devtools::check() and address errors

**Comment by shilohbradley** [comment]
Just need validation

**Comment by shilohbradley** [comment]
- [ ] Create google sheet for import specs

- [ ] Create RMD vignette that reads in google sheet

- [ ] Create dummy data

- [ ] Test functions using dummy data

- [ ] Test functions using real data

- [ ] Save dummy data as a .rda to the package

- [ ] Save google sheet as .dat to the package

**Comment by shilohbradley** [comment]
ready to merge once @AlisonLanski tests it!

**Comment by shilohbradley** [comment]
devtools::check() output

> checking R code for possible problems ... NOTE
  Found the following assignments to the global environment:
  File 'IPEDSuploadables/R/set_report_path.R':
    assign(x = "output_path", value = path, envir = globalenv())

0 errors √ | 0 warnings √ | 1 note x
