### ISSUE TITLE
fix "part = all" write report to start fresh for OM 

### ISSUE THREAD

**Issue by AlisonLanski** [AlisonLanski/IPEDSuploadables#39]
**Describe the bug**
When processing OM, there is only a Part B and Part C, so running a produce_report with part = all repeatedly keeps appending instead of starting a file fresh.

**To Reproduce**
1. produce the OM report multiple times in a row (with parts-all)
2. open the txt file and look at it

**Expected behavior**
Keep this behavior for reports with part A, but adjust the write script for reports without a part A and/or create a generic dummy part A that is blank to process first for the write script

**Additional context**
don't know what other reports might have this problem, but we could look at the upload instructions proactively to try to find them

**Comment by shilohfling** [comment]
grad rates not outcomes measures

**Comment by shilohfling** [comment]
SUCCESS
