### ISSUE TITLE
12 month enrollment lines 11 & 25

### ISSUE THREAD

**Issue by jpfeifer-dsu** [AlisonLanski/IPEDSuploadables#95]
**Which IPEDS Survey/Part has the problem?**
12 month enrollment

**What situation in your data isn't working correctly?**
When I upload the file, graduate students are blank

**Expected behavior**
Looking further, the make_e1d_part_A function is missing lines 11 and 25

**Actual behavior**
see attachement

**Additional context**
I think you need to add the following to the make_e1d_part_A function:

      .data$ISFULLTIME == 1 &
        .data$STUDENTLEVEL == "Graduate" ~ 11,

      .data$ISFULLTIME == 0 &
        .data$STUDENTLEVEL == "Graduate" ~ 25,

![Screen Shot 2022-09-28 at 9 36 42 AM](https://user-images.githubusercontent.com/63427986/192823733-c9a8b151-0281-462c-83d2-6b763ff10cf3.png)

**Comment by AlisonLanski** [comment]
Thanks for finding and noting this update; changes are made and are waiting on final testing for release
